### ISSUE TITLE
Progress Tracker: Implementation of `Linear` class methods 

### ISSUE THREAD

**Issue by klaudiosinani** [klaudiosinani/doublie#6]
## Description

The following issue will act as a progress tracking thread, regarding the implementation of the exposed `Linear` class methods:

### Methods

- [x] `Linear#append(...values)`
- [x] `Linear#filter(fn)` 
- [x] `Linear#forEach(fn)` 
- [x] `Linear#get(index)`
- [x] `Linear#join(separator)`
- [x] `Linear#reduce(fn, accumulator)`
- [x] `Linear#map(fn)`
- [x] `Linear#node(index)`
- [x] `Linear#prepend(...values)`
- [x] `Linear#remove(index)`
- [x] `Linear#reverse()`
- [x] `Linear#set({value, index})`
- [x] `Linear#toArray()`
- [x] `Linear#reduceRight(fn, accumulator)`
- [x] `Linear#insert({value, index})`
