### ISSUE TITLE
Progress Tracker: Implementation of `Circular` class methods 

### ISSUE THREAD

**Issue by klaudiosinani** [klaudiosinani/doublie#7]
## Description

The following issue will act as a progress tracking thread, regarding the implementation of the exposed `Circular` class methods:

### Methods

- [x] `Circular#append(...values)`
- [x] `Circular#filter(fn)` 
- [x] `Circular#forEach(fn)` 
- [x] `Circular#get(index)`
- [x] `Circular#join(separator)`
- [x] `Circular#reduce(fn, accumulator)`
- [x] `Circular#map(fn)`
- [x] `Circular#node(index)`
- [x] `Circular#prepend(...values)`
- [x] `Circular#remove(index)`
- [x] `Circular#reverse()`
- [x] `Circular#set({value, index})`
- [x] `Circular#toArray()`
- [x] `Circular#reduceRight(fn, accumulator)`
- [x] `Circular#insert({value, index})`
- [x] `Circular#toLinear()`
